server:
  port: 8081
  tomcat:
    max-http-header-size: 8192
#  error:
#    path: /app/error
dubbo:
  application: 
    name: opensys
  scan: 
    base-packages: com.lt.lxc
  protocol: 
    name: dubbo
    port: 23457
  registry: 
    address: N/A
logging: 
  file: /usr/log/opensys.log
spring: 
  application:
    name: open
#  redis:
#    host: localhost
#    port: 6379
#    password: 123456
#    database: 1
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0
#    timeout: 5000ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lxc_open?charset=utf8mb4&useSSL=false
    username: root
    password: 123456
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      connection-test-query: SELECT 1
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: com.lt.lxc.configuration.MySQL5InnoDBDialectUtf8mb4
        hbm2ddl:
          auto: update
  profiles:
    active: dev
test:
  username: zhaolei
  
constant: 
  threadCount: 6
  randomGroupCount: 1
  firstIssueNumber: 20191221001
  firstOpenTime: 1576900800000
  intervalTime: 1
